### ISSUE TITLE
Wrong return types

### ISSUE THREAD

**Issue by skoch9** [geometryprocessing/libigl-python-bindings#16]
```
vc, fc = igl.read_triangle_mesh("data/camelhead.off")
bnd = igl.boundary_loop(fc)
bnd_uv = igl.map_vertices_to_circle(vc, bnd)

# bnd_uv = np.ascontiguousarray(bnd_uv)
uv = igl.harmonic_weights(vc, fc, bnd, bnd_uv, 1)
```
gives the error: `ValueError: Invalid type (double, Col Major) for argument 'bc'. Expected it to match argument 'v' which is of type (double, Row Major). `. Converting the array with numpy (see commented out function) works.

**Comment by fwilliams** [comment]
We need to always return row major types in these cases.

**Comment by fwilliams** [comment]
@KarlLeell have you had a chance to look at the `read_*` functions? It might be nice to get these in before the next release tomorrow.
