### ISSUE TITLE
Wrong format problem

### ISSUE THREAD

**Issue by skoch9** [geometryprocessing/libigl-python-bindings#18]
```
v, f = igl.read_triangle_mesh("data/armadillo.obj")
#f = f.astype("int64") 

vs = np.array([0])
vt = np.arange(v.shape[0])

d = igl.exact_geodesic(v, f, vs, vt)
``` 
fails when f is not converted to `int64`. Reading function should probably return consistent types.

**Comment by fwilliams** [comment]
Can you paste the error message?

**Comment by skoch9** [comment]
Thanks! 
`ValueError:` Invalid type (long, Col Major) for argument 'vs'. Expected it to match argument 'f' which is of type (int, Row Major).``

**Comment by fwilliams** [comment]
This is annoying. We can avoid these by not using `npe_matches` at the expense of increased compile times.

**Comment by fwilliams** [comment]
I was thinking about this, and we should return index arrays with the same dtype as `int` in python. On my 64 bit linux machine, these are 64 bit (longs). It seems like a sane default.
